package proyectofinal;

import javax.swing.ImageIcon;


public class Dashboard extends javax.swing.JFrame {
    public ImageIcon icTareasParaHoy = new ImageIcon("computer.png");

    public Dashboard() {
        initComponents();
        this.setResizable(false);
        this.btnTareasParaHoy.setIcon(icTareasParaHoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTareasParaHoy = new javax.swing.JButton();
        btnTareasVencenHoy = new javax.swing.JButton();
        btnTareasCompletas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrearListas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnVerListas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTareasParaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasParaHoyActionPerformed(evt);
            }
        });
        getContentPane().add(btnTareasParaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 79, 144, 160));
        getContentPane().add(btnTareasVencenHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 79, 141, 160));

        btnTareasCompletas.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(btnTareasCompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 79, 156, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setText("TAREAS PARA HOY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 48, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("TAREAS VENCEN HOY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 48, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setText("TAREAS COMPLETAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 51, -1, 14));

        btnCrearListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearListasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 276, 144, 162));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setText("LISTAS");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnVerListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 276, 144, 162));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setText("TAREAS");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTareasParaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasParaHoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTareasParaHoyActionPerformed

    private void btnCrearListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearListasActionPerformed
        frmCrearListas crearLista = new frmCrearListas();
        crearLista.show();
    }//GEN-LAST:event_btnCrearListasActionPerformed

    private void btnVerListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerListasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearListas;
    private javax.swing.JButton btnTareasCompletas;
    private javax.swing.JButton btnTareasParaHoy;
    private javax.swing.JButton btnTareasVencenHoy;
    private javax.swing.JButton btnVerListas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
