package proyectofinal;

import java.awt.Color;
import javax.swing.ImageIcon;


public class Dashboard extends javax.swing.JFrame {
    //Declaracion de iconos para ser seteados en componentes del formulario
    public ImageIcon icTareasParaHoy = new ImageIcon("notification.png");
    public ImageIcon icTareasVencenHoy = new ImageIcon ("fast-time.png");
    public ImageIcon icTareasImportantes = new ImageIcon ("test.png");
    public ImageIcon icCrearLista = new ImageIcon ("lista-de-verificacion.png");
    public ImageIcon icTareas = new ImageIcon ("portapapeles.png");
    public ImageIcon icClose = new ImageIcon ("close.png");
    
    public Dashboard() {
        initComponents();
        //Configuracion general y seteo de iconos a botones
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.btnTareasParaHoy.setIcon(icTareasParaHoy);
        this.btnTareasVencenHoy.setIcon(icTareasVencenHoy);
        this.btnTareasImportantes.setIcon(icTareasImportantes);
        
        this.btnTareasParaHoy.setBackground(Color.white);
        this.btnTareasVencenHoy.setBackground(Color.white);
        this.btnTareasImportantes.setBackground(Color.white);
        
        this.btnListasIcon.setIcon(icCrearLista);
        this.btnTareasIcon.setIcon(icTareas);
        this.btnCloseIcon.setIcon(icClose);       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTareasParaHoy = new javax.swing.JButton();
        btnTareasVencenHoy = new javax.swing.JButton();
        btnTareasImportantes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCloseIcon = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnListas = new javax.swing.JButton();
        btnTareasIcon = new javax.swing.JButton();
        btnTareas = new javax.swing.JButton();
        btnListasIcon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        btnTareasParaHoy.setBackground(new java.awt.Color(255, 255, 255));
        btnTareasParaHoy.setForeground(new java.awt.Color(255, 255, 255));
        btnTareasParaHoy.setBorderPainted(false);
        btnTareasParaHoy.setContentAreaFilled(false);
        btnTareasParaHoy.setFocusPainted(false);
        btnTareasParaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasParaHoyActionPerformed(evt);
            }
        });

        btnTareasVencenHoy.setBackground(new java.awt.Color(255, 255, 255));
        btnTareasVencenHoy.setForeground(new java.awt.Color(255, 255, 255));
        btnTareasVencenHoy.setBorderPainted(false);
        btnTareasVencenHoy.setContentAreaFilled(false);
        btnTareasVencenHoy.setFocusPainted(false);
        btnTareasVencenHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasVencenHoyActionPerformed(evt);
            }
        });

        btnTareasImportantes.setBackground(new java.awt.Color(255, 255, 255));
        btnTareasImportantes.setForeground(new java.awt.Color(255, 255, 255));
        btnTareasImportantes.setBorderPainted(false);
        btnTareasImportantes.setContentAreaFilled(false);
        btnTareasImportantes.setFocusPainted(false);
        btnTareasImportantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasImportantesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAREAS PARA HOY");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAREAS IMPORTANTES");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TAREAS VENCEN HOY");

        btnCloseIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCloseIcon.setForeground(new java.awt.Color(240, 240, 240));
        btnCloseIcon.setBorder(null);
        btnCloseIcon.setContentAreaFilled(false);
        btnCloseIcon.setFocusPainted(false);
        btnCloseIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTareasParaHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTareasVencenHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTareasImportantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addComponent(btnCloseIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCloseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTareasParaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTareasVencenHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTareasImportantes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 570, 500));

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/grap.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 290, 370, 180));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("To Do List");
        kGradientPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 310, -1));

        btnListas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListas.setForeground(new java.awt.Color(240, 240, 240));
        btnListas.setText("Listas");
        btnListas.setBorder(null);
        btnListas.setContentAreaFilled(false);
        btnListas.setFocusPainted(false);
        btnListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListasActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, 70));

        btnTareasIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTareasIcon.setForeground(new java.awt.Color(240, 240, 240));
        btnTareasIcon.setBorder(null);
        btnTareasIcon.setContentAreaFilled(false);
        btnTareasIcon.setFocusPainted(false);
        btnTareasIcon.setMargin(new java.awt.Insets(2, 14, 2, 10));
        btnTareasIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasIconActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnTareasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 70));

        btnTareas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTareas.setForeground(new java.awt.Color(240, 240, 240));
        btnTareas.setText("Tareas");
        btnTareas.setBorder(null);
        btnTareas.setContentAreaFilled(false);
        btnTareas.setFocusPainted(false);
        btnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, 70));

        btnListasIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListasIcon.setForeground(new java.awt.Color(240, 240, 240));
        btnListasIcon.setBorder(null);
        btnListasIcon.setContentAreaFilled(false);
        btnListasIcon.setFocusPainted(false);
        btnListasIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListasIconActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnListasIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 70));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton que abre las tareas para hoy
    private void btnTareasParaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasParaHoyActionPerformed
        frmTareasParaHoy tareasparahoy = new frmTareasParaHoy();
        tareasparahoy.show();
    }//GEN-LAST:event_btnTareasParaHoyActionPerformed

    //Boton que abre las tareas que vencen hoy
    private void btnTareasVencenHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasVencenHoyActionPerformed
       frmTareasVencenHoy vencentareas = new frmTareasVencenHoy();
       vencentareas.show();
    }//GEN-LAST:event_btnTareasVencenHoyActionPerformed

    //Boton que abre las tareas importantes
    private void btnTareasImportantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasImportantesActionPerformed
        frmTareasCompletas tareascompletas = new frmTareasCompletas();
        tareascompletas.show();
    }//GEN-LAST:event_btnTareasImportantesActionPerformed

    //Boton que cierra todo
    private void btnCloseIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseIconActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseIconActionPerformed

    //BOTONES PARA ABRIR LISTAS Y TAREAS YA SEA EN EL ICONO O EL BOTON
    private void btnTareasIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasIconActionPerformed
        frmCrearTarea crearTarea = new frmCrearTarea();
        crearTarea.show();
    }//GEN-LAST:event_btnTareasIconActionPerformed

    private void btnListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasActionPerformed
        frmCrearListas crearLista = new frmCrearListas();
        crearLista.show();
    }//GEN-LAST:event_btnListasActionPerformed

    private void btnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasActionPerformed
        frmCrearTarea crearTarea = new frmCrearTarea();
        crearTarea.show();
    }//GEN-LAST:event_btnTareasActionPerformed

    private void btnListasIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasIconActionPerformed
        frmCrearListas crearLista = new frmCrearListas();
        crearLista.show();
    }//GEN-LAST:event_btnListasIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseIcon;
    private javax.swing.JButton btnListas;
    private javax.swing.JButton btnListasIcon;
    private javax.swing.JButton btnTareas;
    private javax.swing.JButton btnTareasIcon;
    private javax.swing.JButton btnTareasImportantes;
    private javax.swing.JButton btnTareasParaHoy;
    private javax.swing.JButton btnTareasVencenHoy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
