package proyectofinal;

import javax.swing.ImageIcon;


public class Dashboard extends javax.swing.JFrame {
    public ImageIcon icTareasParaHoy = new ImageIcon("computer.png");
    public ImageIcon icTareasVencenHoy = new ImageIcon ("2.png");
    public ImageIcon icTareasCompletas = new ImageIcon ("3.png");
    public ImageIcon icCrearLista = new ImageIcon ("1.png");
    public ImageIcon icTareas = new ImageIcon ("libros1.png"); 
    
    public Dashboard() {
        initComponents();
        this.setResizable(false);
        this.btnTareasParaHoy.setIcon(icTareasParaHoy);
        this.btnTareasVencenHoy.setIcon(icTareasVencenHoy);
        this.btnTareasCompletas.setIcon(icTareasCompletas);
        this.btnCrearListas.setIcon(icCrearLista);
        this.btnVerListas.setIcon(icTareas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTareasParaHoy = new javax.swing.JButton();
        btnTareasVencenHoy = new javax.swing.JButton();
        btnTareasCompletas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrearListas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnVerListas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTareasParaHoy.setBackground(new java.awt.Color(204, 255, 204));
        btnTareasParaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasParaHoyActionPerformed(evt);
            }
        });
        getContentPane().add(btnTareasParaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 144, 160));

        btnTareasVencenHoy.setBackground(new java.awt.Color(204, 204, 255));
        btnTareasVencenHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasVencenHoyActionPerformed(evt);
            }
        });
        getContentPane().add(btnTareasVencenHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 141, 160));

        btnTareasCompletas.setBackground(new java.awt.Color(255, 204, 204));
        btnTareasCompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasCompletasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTareasCompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 156, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setText("TAREAS PARA HOY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("TAREAS VENCEN HOY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setText("TAREAS COMPLETAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 14));

        btnCrearListas.setBackground(new java.awt.Color(214, 234, 248));
        btnCrearListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearListasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 144, 162));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setText("LISTAS");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        btnVerListas.setBackground(new java.awt.Color(251, 238, 230));
        btnVerListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 144, 162));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setText("TAREAS");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTareasParaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasParaHoyActionPerformed
        frmTareasParaHoy tareasparahoy = new frmTareasParaHoy();
        tareasparahoy.show();
    }//GEN-LAST:event_btnTareasParaHoyActionPerformed

    private void btnCrearListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearListasActionPerformed
        frmCrearListas crearLista = new frmCrearListas();
        crearLista.show();
    }//GEN-LAST:event_btnCrearListasActionPerformed

    private void btnVerListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListasActionPerformed
        frmCrearTarea crearTarea = new frmCrearTarea();
        crearTarea.show();
    }//GEN-LAST:event_btnVerListasActionPerformed

    private void btnTareasVencenHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasVencenHoyActionPerformed
       frmTareasVencenHoy vencentareas = new frmTareasVencenHoy();
       vencentareas.show();
    }//GEN-LAST:event_btnTareasVencenHoyActionPerformed

    private void btnTareasCompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasCompletasActionPerformed
        frmTareasCompletas tareascompletas = new frmTareasCompletas();
        tareascompletas.show();
    }//GEN-LAST:event_btnTareasCompletasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearListas;
    private javax.swing.JButton btnTareasCompletas;
    private javax.swing.JButton btnTareasParaHoy;
    private javax.swing.JButton btnTareasVencenHoy;
    private javax.swing.JButton btnVerListas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
